tasks:
  deploy:
    command: |
      npx -y vercel@37.6.0 pull --yes ${HHH_VERCEL_PREVIEW+--environment=preview} ${HHH_VERCEL_PROD+--environment=production} ${VERCEL_TOKEN:+--token=$VERCEL_TOKEN} &&
      npx -y vercel@37.6.0 build ${HHH_VERCEL_PROD+--prod} &&
      npx -y vercel@37.6.0 deploy --prebuilt ${HHH_VERCEL_PROD+--prod} ${VERCEL_TOKEN:+--token=$VERCEL_TOKEN}
    inputs:
      - $VERCEL_*
      - $HHH_VERCEL_PREVIEW # Use to turn on "preview" mode.
      - $HHH_VERCEL_PROD # Use to turn on "production" mode.
    options:
      runInCI: false
      shell: true
    platform: node
