name: CI (daily)

on:
  schedule:
    # Run at 7 AM AEST, some tests check if packages are up to date (e.g. `expo
    # doctor`). Without a schedule then random pull requests can fail.
    - cron: 0 17 * * *

jobs:
  moon-ci:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1
        with:
          auto-install: true

      - run: moon ci
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
