name: Expo EAS Build
on:
  push:
    branches:
      - "main"
      - "releases/**"
    paths:
      - "projects/frontend/app.json"

jobs:
  update:
    name: EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Install dependencies
        uses: "moonrepo/setup-toolchain@v0"

      - name: ğŸš€ Build app
        run: moon run frontend:eas -- build --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
