name: Expo EAS Update
on:
  push:
    branches:
      - main
      - releases/**

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸš€ Publish update
        run: |
          moon run frontend:eas -- update --auto --non-interactive
          moon run frontend:upload-sentry-source-maps
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
