name: Test PR

env:
  NEON_BRANCH_NAME: github_test_pr_${{ github.event.number || 'unknown' }}
  NEON_DATABASE_NAME: hao

on:
  pull_request:

jobs:
  test_database:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: ğŸ— Setup database branch for running tests
        uses: neondatabase/create-branch-action@v5
        id: create-branch
        with:
          api_key: ${{ secrets.NEON_API_KEY }}
          branch_name: ${{ env.NEON_BRANCH_NAME }}
          database: ${{ env.NEON_DATABASE_NAME }}
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          username: ${{ secrets.NEON_USERNAME }}
      - name: ğŸ”‘ Save Neon test database credentials
        run: echo "DATABASE_URL=${{ steps.create-branch.outputs.db_url }}" >> ./projects/api/.env.local
      - name: ğŸ“¦ Install test dependencies
        uses: "moonrepo/setup-toolchain@v0"
      - name: ğŸš€ Run database tests
        run: moon run api:dbMigrate
      - name: ğŸ— Clean up database branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: ${{ env.NEON_BRANCH_NAME }}
          api_key: ${{ secrets.NEON_API_KEY }}
        if: ${{ always() }}
