name: PR

on:
  pull_request:

jobs:
  moon-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fixes:
          #
          # Ã— CI requires a full VCS history to operate correctly. Please avoid shallow checkouts.
          fetch-depth: 0

      - uses: moonrepo/setup-toolchain@v0.3.1

      - run: moon ci
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  database:
    runs-on: ubuntu-latest
    env:
      NEON_BRANCH_NAME: github_test_pr_${{ github.event.number || 'unknown' }}
      NEON_DATABASE_NAME: hao
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ— Create database branch for running tests
        uses: neondatabase/create-branch-action@v5
        id: create-branch
        with:
          api_key: ${{ secrets.NEON_API_KEY }}
          branch_name: ${{ env.NEON_BRANCH_NAME }}
          database: ${{ env.NEON_DATABASE_NAME }}
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          username: ${{ secrets.NEON_USERNAME }}

      - name: ğŸ”‘ Save Neon test database credentials
        run: echo "DATABASE_URL=${{ steps.create-branch.outputs.db_url }}" >> ./projects/api/.env.local

      - name: ğŸ“¦ Install test dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸš€ Run database tests
        run: moon run api:dbMigrate

      - name: ğŸ—‘ï¸ Delete database branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: ${{ env.NEON_BRANCH_NAME }}
          api_key: ${{ secrets.NEON_API_KEY }}
        if: ${{ always() }}

  api-vercel-preview:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run api:vercel -- pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build Project Artifacts
        run: moon run api:vercel -- build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: moon run api:vercel -- deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  frontend-vercel-preview:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run frontend:vercel -- pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build Project Artifacts
        run: moon run frontend:vercel -- build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: moon run frontend:vercel -- deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  static-vercel-preview:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run static:vercel -- pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build Project Artifacts
        run: moon run static:vercel -- build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: moon run static:vercel -- deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
