name: Preview Vercel (frontend)

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

on:
  push:
    branches-ignore:
      - "main"

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Install dependencies
        uses: "moonrepo/setup-toolchain@v0"

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run frontend:vercel -- pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build Project Artifacts
        run: moon run frontend:vercel -- build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: moon run frontend:vercel -- deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
