name: Release

on:
  push:
    branches:
      - main

jobs:
  api-vercel-production:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run api:vercel -- pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build Project Artifacts
        run: moon run api:vercel -- build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: moon run api:vercel -- deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  frontend-vercel-production:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run frontend:vercel -- pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build Project Artifacts
        run: moon run frontend:vercel -- build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: moon run frontend:vercel -- deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  static-vercel-production:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        uses: moonrepo/setup-toolchain@v0.3.1

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run static:vercel -- pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build Project Artifacts
        run: moon run static:vercel -- build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy Project Artifacts to Vercel
        run: moon run static:vercel -- deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
