name: Release

on:
  push:
    branches:
      - main

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: ğŸš€ Migrate database
        run: moon run app:dbMigrate
        env:
          DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}

  app-vercel:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_APP }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run app:yarnRun -- vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build and deploy
        run: moon run app:deployVercel
        env:
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  static-vercel:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: ğŸ”‘ Fetch Vercel secrets
        run: moon run static:yarnRun -- vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Build and deploy
        run: moon run static:deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  app-eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-tools

      - name: ğŸš€ Build and deploy
        run: moon run app:deployEasUpdate
        env:
          EXPO_PUBLIC_REPLICACHE_LICENSE_KEY: ${{ secrets.EXPO_PUBLIC_REPLICACHE_LICENSE_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
